server:
  port: 8888
#Eureka
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:9102/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: personsMS
          uri: http://localhost:9001/
          predicates:
            - Path=/personnes/**
        - id: reportsMS
          uri: http://localhost:9002/
          predicates:
            - Path=/reports/**
management:
    endpoints:
      web:
        exposure:
          include: "*"