server:
  port: 9103
#Eureka
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:9102/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: personsMS
          uri: http://localhost:9001/
          predicates:
            - Path=/personnes/**
            - Path=/auth/**
        - id: reportsMS
          uri: http://localhost:9002/
          predicates:
            - Path=/reports/**
management:
  endpoints:
    web:
      exposure:
        include: "*"